trigger:
  branches:
    include:
    - main
    - feature/*
variables:
- name: service_connection
  value: 'newsc'
- name: workdir
  value: '$(System.DefaultWorkingDirectory)/Infra'

jobs:
  - job: Terraform_Execution
    displayName: 'Terraform Init/Plan (and Apply for main)'
    pool:
      name: New_agent
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workdir)
        backendServiceArm: $(service_connection)
        backendAzureRmStorageAccountName: 'dkcstorageaccount'
        backendAzureRmContainerName: 'dkccontainer'
        backendAzureRmKey: 'newtf.tfstate'
    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(workdir)
    - task: TerraformTask@5
      displayName: Terraform Format
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: $(workdir)
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: $(service_connection)
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workdir)
        environmentServiceNameAzureRM: $(service_connection)
  - job: Manual_Approval
    displayName: 'Manual Approval before Apply'
    dependsOn:
    - Terraform_Execution
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    pool:
      name: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Approve to proceed with Terraform Apply.'
        approvers: 'dkc.hcl@gmail.com'
        notifyUsers: 'dkc.hcl@gmail.com'
        onTimeout: 'reject'
        timeout: '1d'
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    dependsOn:
    - Manual_Approval
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    pool:
      name: New_agent
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init (Again)
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workdir)
        backendServiceArm: $(service_connection)
        backendAzureRmStorageAccountName: 'dkcstorageaccount'
        backendAzureRmContainerName: 'dkccontainer'
        backendAzureRmKey: 'newtf.tfstate'
    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(workdir)
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: $(service_connection)

